language: bash
sudo: required
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- |
  if [[ "${TRAVIS_COMMIT_MESSAGE}" == "[gitflow]"* ]] && [[ "${TRAVIS_BRANCH}" != v[0-9]* ]]; then
    travis_terminate 0
  fi
before_script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script:
- |
  if [[ "${TRAVIS_BRANCH}" == release-* ]]; then
    QUALIFIER=-frozen-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    QUALIFIER=-dev-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    QUALIFIER=""
  else
    QUALIFIER=-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  fi && ./.travis.scripts/mvn.sh build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'${QUALIFIER}
- "./.travis.scripts/mvn.sh -Dmaven.site.skip=true clean verify -B -e -V"
after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]] || [[ "${TRAVIS_BRANCH}" == release-* ]] || [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    ./.travis.scripts/mvn.sh sonar:sonar
  fi
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    ./.travis.scripts/mvn.sh -P github-site site  fi
deploy:
  provider: script
  script: "./.travis.scripts/mvn.sh -Dmaven.site.skip=true -P stage-devel-bintray
    deploy"
  skip_cleanup: true
  on:
    all_branches: true
branches:
  except:
  - gh-pages
  - master
env:
  global:
    secure: fmwvuI4/CUdGwTFrIA8NsXESbFjqUQbZjRfZJXTtlJ42YpBLweQCQsB1IUGavWJwneNaNsu2y0m2reQOzszn1fPuwqaiQpEM+F2tWdg7WBGmbD8TeLQugd0lQE03Cb8n4fXpBuXKwD95Rbru4IQPl2iklCHTs9BcfnXGRx+QOqQvTp9AZ8ZWVphsMWwS0TU2cc4Ox+DAfI7hXq8WGWwvCeDO8CplUMcQD2nmBgB59KNoQOEEr6u00PdYRt92WKyXr1nX7VegjnaXTivPqqCSHB+CLTAd/21zdEXID2wP1WJCq2mMMM5fT4XSR4zsY7sFxL0bCQcnzw9LO48Vk9CG4xaCqNCFtapaNyn4SESZ6XzmdGs+uA9KffkcIuCtydmcvy0HcFcQyJvj5ODu2X1hhtcoNeJoAului8q9s/zmglcDlBdNUIwtdT/4zmgvgt1EnFwu/VDqNshBjhn4Y9TliV3FjI31bHTFCAA9ZZEywdEumBKvhz4RYg2URCw7Hw/lYUkr4SA0EZPjCJKHRFz3pw7Sp2b+Ik1s/hUTzAWBW1xzR2u7KS8LGanZRlk0mvdTxrC5bymsoB4+KkkJsuBw99mEXnC1E/xNcYXT2k2NDjXX8GvFiL8AO4gntMgzy6cC3IP2Wv3BvRyDNbK0TnzOq64tkBdyta31Qd7SphjFn9o=

