language: bash
sudo: required
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- |
  if [[ "${TRAVIS_COMMIT_MESSAGE}" == "[gitflow]"* ]] && [[ "${TRAVIS_BRANCH}" != v[0-9]* ]] && [[ "${TRAVIS_BRANCH}" != development ]] && [[ "${TRAVIS_BRANCH}" != release-* ]]; then
    travis_terminate 0
  fi
before_script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script:
- |
  if [[ "${TRAVIS_BRANCH}" == release-* ]]; then
    QUALIFIER=-frozen-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    QUALIFIER=-dev-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    QUALIFIER=""
  else
    QUALIFIER=-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  fi && ./.travis.scripts/mvn.sh build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'${QUALIFIER}
- "./.travis.scripts/mvn.sh -Dmaven.site.skip=true clean verify -B -e -V"
after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]] || [[ "${TRAVIS_BRANCH}" == release-* ]] || [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    ./.travis.scripts/mvn.sh sonar:sonar
  fi
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    ./.travis.scripts/mvn.sh -P github-site site  fi
deploy:
  provider: script
  script: "./.travis.scripts/mvn.sh -Dmaven.site.skip=true -P stage-devel-bintray
    deploy"
  skip_cleanup: true
  on:
    all_branches: true
branches:
  except:
  - gh-pages
  - master
env:
  global:
  - secure: C+nk4tg+k0qnnKijhGI6kBCM46nxeW6Rb/au8Fk3YUlJVG0NPbE1NexTNslo5bKJwCypcJ2kPbh0uz87awNI/eUxo54/aM8WThnf5siEkOOvxmursLz2YAK2ugvUSIU8s5u72J3vWSgaQIl03HHXvj9hgCt3zksz4oFNlGs+5a/rPJ6xgSVz3d0b+2BIHwkMOtwBqpwYsMA0OaRHYEb3ctPGNJKWlFEoA9Xa9tf5L9iVtMeZbuXCLqUBmi08CAdc1Km97617X6z/uPDa79KUKB6zPAu+/MR9sDSHHfPlZEtFv+skPttz8jhps6jzj12VvhCfPquyd1+1kFpkbdod+A2wGh6XEwPuNjsQ2eIbVpgTAeJSRNZetIJys2cTk6AbRFeegq66zdcpQHYKTgK+LlwPYouMXwd397TjmZ8IA75dD5FnJqKnE/TqpmdGdM2lcylqJ2/GRGWZA+HMc2npcE+kNGhP16DcG7iqw4t1aQVpCTu22V5Mk0nRKAKA6eSW3qr8PgAH4Fv8BRJqR1cWv01x5iFt3TSUzV4voQTJmeXeJ3fKjL2DSRgaleD6qWanh3JJzaQ4aEeR5rd9kIe2Thm6dFfyca41esw5S+6iHOjrOi77z8nIs5pQ4n6QrZJC6yjNyy/aSutjUrnbQ/5pZ+ZQuMCV7pOMKW1YXPp4dLw=
  - secure: JGYkdvGlWNh36IGHK2ACc95gJ8CaQHHUeAADD0QpbKQhTP9ICf80oLcbnvnldYOW/5cVTqFEfbxZWeb4owtTiPEKi6BSKd9smDuaeaOPoJMi5WVlI9yWUjqat9EkHCRMUlqiy2oWOKWOSgFypm/oOL2DhYTDuarTDXXXRnjsQj4fuTqh8rRo6cLg1Z+F9Nan+64Dl8wHR+ulL6vD5LApg6LdgSYpFMTtKug4ksnXVwEiaf1b55tqmc+3evf0vxxa1CZWZnTkkyGJ3TWhQs64qRclUHywyCcVLeEBWlzwFHDgXxj4xQVGKwPqT5KNgYysx2CRDEHur8JhtMeKJE4ahGScLvZgAIbNgKDXzZYB93S4i+PZBAk9OFtS2UqERsHBgtygvy8caZeLcIJvnpYjGvTPcqOrbFqvTGRCZbR2Ujj+bLLZeo7icekVagdUayuRatTFCLHe3mz9THk2hgYLki4G7M3yqyFNSzqYR1aj7QZlHO/vQRNKFQGDVVOH39haYZCjy3o9TZwwlOsJgDm1zuWKO57vetn5afRwJ2z9abE2UF4Gts7HvdB3eSJCUmwyhp3nKFgHuDAQRxh3PtxJlxrXLFevxYcmo5XgLViprKgnnfxnPvYurF2gL4A0DDkD7ht5NJvaAg4w6reOXNGjzOZV96x72HkjuuA7gElFKl0=
