language: bash
sudo: required
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- |
  if [[ "${TRAVIS_COMMIT_MESSAGE}" == "[gitflow]"* ]] && [[ "${TRAVIS_BRANCH}" != v[0-9]* ]]; then
    travis_terminate 0
  fi
before_script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script:
- |
  if [[ "${TRAVIS_BRANCH}" == release-* ]]; then
    QUALIFIER=-frozen-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    QUALIFIER=-dev-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    QUALIFIER=""
  else
    QUALIFIER=-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  fi && ./.travis.scripts/mvn.sh build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'${QUALIFIER}
- "./.travis.scripts/mvn.sh -Dmaven.site.skip=true clean verify -B -e -V"
after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]] || [[ "${TRAVIS_BRANCH}" == release-* ]] || [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    ./.travis.scripts/mvn.sh sonar:sonar
  fi
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    ./.travis.scripts/mvn.sh -P github-site site  fi
deploy:
  provider: script
  script: "./.travis.scripts/mvn.sh -Dmaven.site.skip=true -P stage-devel-bintray
    deploy"
  skip_cleanup: true
  on:
    all_branches: true
branches:
  except:
  - gh-pages
  - master
env:
  global:
  - secure: fmwvuI4/CUdGwTFrIA8NsXESbFjqUQbZjRfZJXTtlJ42YpBLweQCQsB1IUGavWJwneNaNsu2y0m2reQOzszn1fPuwqaiQpEM+F2tWdg7WBGmbD8TeLQugd0lQE03Cb8n4fXpBuXKwD95Rbru4IQPl2iklCHTs9BcfnXGRx+QOqQvTp9AZ8ZWVphsMWwS0TU2cc4Ox+DAfI7hXq8WGWwvCeDO8CplUMcQD2nmBgB59KNoQOEEr6u00PdYRt92WKyXr1nX7VegjnaXTivPqqCSHB+CLTAd/21zdEXID2wP1WJCq2mMMM5fT4XSR4zsY7sFxL0bCQcnzw9LO48Vk9CG4xaCqNCFtapaNyn4SESZ6XzmdGs+uA9KffkcIuCtydmcvy0HcFcQyJvj5ODu2X1hhtcoNeJoAului8q9s/zmglcDlBdNUIwtdT/4zmgvgt1EnFwu/VDqNshBjhn4Y9TliV3FjI31bHTFCAA9ZZEywdEumBKvhz4RYg2URCw7Hw/lYUkr4SA0EZPjCJKHRFz3pw7Sp2b+Ik1s/hUTzAWBW1xzR2u7KS8LGanZRlk0mvdTxrC5bymsoB4+KkkJsuBw99mEXnC1E/xNcYXT2k2NDjXX8GvFiL8AO4gntMgzy6cC3IP2Wv3BvRyDNbK0TnzOq64tkBdyta31Qd7SphjFn9o=
  - secure: iIsb+oOlJA5A4OVSzGBX/+9+OQ3khX15HJq+lVsGVqEubL1stJZ39ivXqq6IW+QfsDoqMJg6HWCnsOE0AFMrwzSvRXSSi4B+w9wTkmMSADt36Sj1szK3HOl78Gkex7SLdxMHZRkS9gPaQhM9kBjc4vHzGXfZdV6LZATSMXI8oqVcUaq7WU8Rn36FMbnunw2AY3Y1GN+C7mS+zORUDQGuumy894d13gvgi3OCNdWcNIeRx5UA+GHM9tmhy4JB7bL64z9YRydDiYFfSjOR9hta7RzPmPDoQGd98APqJMs62s1L+1yiQyp37HIEmlW6Ngg/PY18+uoNoqYNmCR5NhPCELf4wc8Rd/6qVs2uV2Zt1IG59Kq4vnPfcCRccAMz8cMz4U9dlgWUPRiKdDioIVm35zkUXto1h4u3QRBItKFx+mAk7WzA+vsOFgb0wtuN20LpkMGAVUe6fdPdT7vUHGuJKMlPi6ZIeZJw5m6rVWlswduBClxRVU7h6EhOJ0btR28XEdqKiSy0hdXuA+9bV7YZduAJ+0IWPWaBO7tVFcIdD4upxzCyta+cRhdJWFgJAVvKu/PcwsIRlzFBJETtDDeXYWgJwODctZ92TFI5IgYmjEam1rBy6U1wD9gLCgAM9kwqXdv65wYMoowfpIyLR53SRtqlTQbD5y+4+/ZTmtDlKy0=
  matrix:
    secure: NX+sDFIzCNTMUUxZETbGf0SIe5IdlNNN2mIitiCXc9EDrOKWVa0zq5uvINs2wioyoKDzyK1j4AJv+Eif9KasSAxk+px6N+Y0lAqDuCMrbRRYDIbVAfsKZ85l2ClQG1tEd6sWtcgfavsrdlcJB4mHItG+C1BF/OjDtS2OwmeJ7oXiQh6xXv31MS6uCrQP35Q1P/VjJ6jBnYsoHV+0eRa1b2TganD23EWsAVb0th/LzjNtz5+tvqwQyt8sHECLWGiqYbl/15ytWd59rMIvEjLzmtmY4xTW0KPXXjakS9YOCR4UQoeJJ3AX86eNg9yT0DPG5FXyao7+FzS/8ml9/hWPqC7cqz5hOF7YXPneazJ0Nix4YfVlkd7GfaLA1J1ZXDVlIofQtql9iFk0E+/fkV4/7+ReAEI4li16bgeeA/B55ijaOhsD4KyWa6ec/FTKd9EArLj9gSzV2BrP90YQZYKtIVb92XfgSzjqFd9ouzKjm8PQlUdSI6sq8SXAY6+9Zr4dmesPaFre/pn5pMVUTAGArMrbUypN6+nIP36F4V2BZDcYXdTokZRMz2mDsSebcMrsK9Hcp9xWjLG6152yRrGjJ+yFxPtgOiVd7icNXwzxGfajs9FE0Fbw6e5DSwQUEPXOWR0FiYe68SiYvDOQHgD+aCti7rUwfr0XieBgo+44TsY=
