language: bash
sudo: required
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- |
  if [[ "${TRAVIS_COMMIT_MESSAGE}" == "[gitflow]"* ]] && [[ "${TRAVIS_BRANCH}" != v[0-9]* ]]; then
    travis_terminate 0
  fi
before_script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script:
- |
  if [[ "${TRAVIS_BRANCH}" == release-* ]]; then
    QUALIFIER=-frozen-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    QUALIFIER=-dev-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    QUALIFIER=""
  else
    QUALIFIER=-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  fi && ./.travis.scripts/mvn.sh build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'${QUALIFIER}
- "./.travis.scripts/mvn.sh -Dmaven.site.skip=true clean verify -B -e -V"
after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]] || [[ "${TRAVIS_BRANCH}" == release-* ]] || [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    ./.travis.scripts/mvn.sh sonar:sonar
  fi
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    ./.travis.scripts/mvn.sh -P github-site site  fi
deploy:
  provider: script
  script: "./.travis.scripts/mvn.sh -Dmaven.site.skip=true -P stage-devel-bintray
    deploy"
  skip_cleanup: true
  on:
    all_branches: true
branches:
  except:
  - gh-pages
  - master
env:
  global:
  - secure: Byf9H3nvqvcBCSKCUAwV3aV1Leb/zQ+TQ+kR/Ra8UmUFZjt2c9oYNnTySrxP84HV4TjsoE4/+83qCKtBguWTWDQ9WgwdSPtFY8A7AH7UBn0R3NzPU8euxQcFcreWCSs5LfTn58eM9nATdFmcEddkwPAuBM9qS/QpnhDkahasLe/kwpikMLnajmHtTNYE1RJWfS7nFDgGeycmEDqt0mU7PgmFVsEWyc7Izfud3fPCkZHqOPs5CXeKEguF8k3m/8JF4DvyznrmHI9lDb3CA8iMjjboHUKd/HGpxO+/ybMYWIsNIaH0wctN6y10oIKWj2MY8imsw0X223qLrUbad49isypitJpb8n3jXjNzck50SWbAMzZgtMDVB15I4aZ3OP+XN8l+2nyMkjWU0wyg1XO2cbFrjBQDyyuFnN0VbAaZk2rZVyBztj22KEXFEVvSn97EDgtM46rEO22i/hMFfmJVbIhXVndYkl3wlYCahab/TVQDIXvRH9Wrd5LLv9+yyzNZjMUFQ8Vm7Nf4keLUzlZuajluU99L8wXgv+QwXPmLOYW4FLQgHU/qp5Q25i9xpHyTFg6+WXktTKZze0qkhy6nd21JRCy0io92ZxcmRUyw1UqrUswPnIRt/gZ/q4pjVo6MTmv1x/jsn9JQ/jtkTnLkYgAdGuln6xNsIvc9/REMZSQ=
  - secure: aiivZUDipi5A5VeufBpHFzy3qZDANjoqiPtX4V9M5lsov7rRnhg8C+eRe6qq0DmkeP4xq2+SCdkMIKgj2kINjNNVkBxTrg+bUxEHvZPANqzxo5LCoUeCQqyyaZqkiXu9wgy9X8vpnljA/IKgOsoTdQVubmjuK+Lu7SevZEUI72VfjtbSJzlTr435duTO+LK7vMim5BQhgjsO5FHweds/jfLbcij4QevuFtAJs93iYpkZ6HhJfkXgL2JvLxxIxc7nHe6+7p6sPRgkujP0W77A9rVyHn4QusvZRr765lzYfw2CqruxIOHHIyNKzW8wmx7SHAh375mpeCVznNjeF7/iZitLyn+bVhrFuZsax8YfbMKyOmH2ZMbOF0oIlTQmPr7mPAAAKRE9Obm7ijYmOC0eQdcYO1W1yb6V7kNl5w3sW+LU8tHo9Nqe0ucmmPXLhot+aH9ngDOD/gJw46elLikcoi1N++sY71/R+l5uZjE5cM635CJe9tls1Sevw+pTb+zvH94kZ2Bx2TViSvwEvsh5LeXQ0qdgL7bcO4jtzxOTXfENLukPGL5rAHnRu2DjmpnMbt3zFRp77QJHLCyDHdLO9N8pTc2loiveWEBdmwvJZ4pjfFuPqRN/zPMufWORng36OHTGO0bRh1BQCmTzu2yG8aLDWOfXFzti/Ku1605yd8o=
  - secure: cDNzXJoSKdKenly/UbBom9sGnWFGn7OJez2944Htt/Bk5KheaxrvyaGUfagq/rhjZ63XaaXMzAVhhUT8dmcZDiSin4j/o1Sgc5PWFL1flFzg8I6P44K7nnYX8emW6NFEL/SW86tISeLqSHd7btUed96n2bTpQ/XjyDlTpsL0OCjFnvnyenptNBj/uNNhnE7/ayW+yGH8tEj/IjZLfVnZkAbT/hJid9Be7w9mrd/1mwZ1nTvZ19pGE+haz5Z3hkFBYgO5m6T+lfS4NN2p2b28dTxIC3Txvi9VCXqSZdq2YIVseX5+LSx9zslcRb6/L5ZypZHzotxa6RRug3WExCGx+TDkAKyHUr0sDitmi/BlG/8vv/ZuqATJwdsW6unHTSX8w0wjTKIssHXKxmFP27wiTZa143taacY59moeFdZhWJPOZBdNdFpGFHOYg55VfWf80AcUn9W7vx/UftpqFTMgjjAQzJ1mfyqMlE6bYh6asVQP7z/WoI4jjdc8RP61CUvlb3Z1g7nvjxzIU9/fZv/yuL4aSoHPrW8RXqO1x5oVet9kV89RAqD9qo83hCrO4uX8TMAQZZzlm56bZpDjGM9Ho3Ey5DLhx2zhgjsmUlCZRYYG8VE4NGih9I6ZxpHWGz4uHMcPGrqVY060ljQL2ORcwfozAxhb1J7Ha/HrkZzVJJo=
  matrix:
  - secure: NX+sDFIzCNTMUUxZETbGf0SIe5IdlNNN2mIitiCXc9EDrOKWVa0zq5uvINs2wioyoKDzyK1j4AJv+Eif9KasSAxk+px6N+Y0lAqDuCMrbRRYDIbVAfsKZ85l2ClQG1tEd6sWtcgfavsrdlcJB4mHItG+C1BF/OjDtS2OwmeJ7oXiQh6xXv31MS6uCrQP35Q1P/VjJ6jBnYsoHV+0eRa1b2TganD23EWsAVb0th/LzjNtz5+tvqwQyt8sHECLWGiqYbl/15ytWd59rMIvEjLzmtmY4xTW0KPXXjakS9YOCR4UQoeJJ3AX86eNg9yT0DPG5FXyao7+FzS/8ml9/hWPqC7cqz5hOF7YXPneazJ0Nix4YfVlkd7GfaLA1J1ZXDVlIofQtql9iFk0E+/fkV4/7+ReAEI4li16bgeeA/B55ijaOhsD4KyWa6ec/FTKd9EArLj9gSzV2BrP90YQZYKtIVb92XfgSzjqFd9ouzKjm8PQlUdSI6sq8SXAY6+9Zr4dmesPaFre/pn5pMVUTAGArMrbUypN6+nIP36F4V2BZDcYXdTokZRMz2mDsSebcMrsK9Hcp9xWjLG6152yRrGjJ+yFxPtgOiVd7icNXwzxGfajs9FE0Fbw6e5DSwQUEPXOWR0FiYe68SiYvDOQHgD+aCti7rUwfr0XieBgo+44TsY=
  - secure: FQCXxMPup034Bnlz3VX7XvgtqTW88BDh+Oc74WiqK03qNzUTSbP3fTnaHJd3A4o9KjqAMFGlvCAYpVw8GlxCyQv7EZK/mX7JYsYR/Okl1xouUVy8jGSiAiKZ0yniZwT8fprQAx2YPOJwqYFl+wOOjDV+CddmZhkf0vpgyLyCIHdN93ZzSFGUUgG7WwAXTvwLaQU2WjGynYsDtc9ZLFQbUHQhDU0YvdmXoF+skjVhdLRchAmtIlMO2Q7aHH8FpW+4B3QlxW2Rz5QsGhGQTtoOyZqRIQ1CUuDmDd/8HSyN43MNGnUt6u8xPy7mMrbTnsQRgztNgiV0zXvVb6hG7ChGtKunkp1WQITIC3kD+QCKe2ga1nyM6YeUlD28+ezpNfOgWTtJU3zinYrCmskaISqV2Tj3usQbH+yesptI1OodRDhuDEZoJvrsqtQYM1QOEuiBO0k+LWkltLnBQZ6kJG3CHdreQJREl+Q5+tLya7XdmaCR/dwT9d5+PvYPh9T8ljFs07IutqAuN+mA8Jg3QSTz/fNeTiOkfVhs6A9njTyaKyqdGH5nXmu1r3m/CLYyTtow4RAHnT9xsTyJAENk3ZRpkWUfhcYkjMvi4DrxczCY4qBNCkS8LhmMjNzQL31WVal4c1CSCJnjc9Pu50qZTyI2GplP8W5eoNTui2ciTeCfkDg=
  - secure: TTjnULCCegm0nsBxtLa2kWNCD7LvvD1vdfIAqerLWhDve6AXLuqfVQRiA+noBX2T+F13/OMk2m2mlOBoOIJIx6Q9EHmoPWt6fodHW8FMV9oZJXb1uPRXvQwHytibTtvH6mpYNpPw2GB6t9/Go8lrBn088NCFB3Gms5ZP5h/ao8YeQvYVGh0G+frMjLnKiLKjQzh2yNJsCPBW+JgcBgzVNxqoCV6/cE+8VV1bAbVG6KSFa8RG7/9See7ZKcclcyYO/cH/EH1vJV4rzSaQzYD2ZHggBxrfN3696Of9kvrfsxKuGRKqJk72qmPOdrSx98r1nid0dlQBqaQ7Tq13ijE3LdTc7JUbvB7FZlUxhCu8We71I/ucjJ9NNY1JUsoFQoEtLT94dsIT+EIxbgPE1j6AmTXsK79FYq+Gd9k0hzOrEqs5O/VolHM8k3NqcdWbYIpLkO+ShPYaq3NshvK08f9rddgcKquC1P48MmgCX2VVScZ4yt4w00lLz92ls7EeWRFQQfIicnZIXLlIr2PHsvhGKzN0ClS5dJFnrVlpZAxcVBwg4Y5FtEKu+kSFHgOND1XlEYF+5P08U64eiNWSQtagKuB6XwCFyJOKqcQFWYiK+QIBi7EUic0mQ3fBBQfMgqS63bwsq1BvL/JCaasOAAh5LZbU0NO5h5iAjGzCuADr2EY=

