ALTER TABLE PROFILE_JOB DROP CONSTRAINT FK_PROFILE_JOB_Profile_ID
ALTER TABLE PROFILE_JOB DROP CONSTRAINT FK_PROFILE_JOB_jobs_ID
DROP TABLE JOB CASCADE
DROP TABLE PROFILE CASCADE
DROP TABLE PROFILE_JOB CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
